/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-03-07 13:12:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/kkm/Desktop/mySpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/myWebProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/join/../header/header.jsp", Long.valueOf(1615112894688L));
    _jspx_dependants.put("/WEB-INF/views/join/../header/nav.jsp", Long.valueOf(1615115795311L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1609506581910L));
    _jspx_dependants.put("/WEB-INF/views/join/../footer/footer.jsp", Long.valueOf(1615115637335L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/mycss/join.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Test</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 css 사용 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<!--  부트스트랩 js 사용 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--  부트스트랩 js 사용 -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- nav     footer  css -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/mycss/nav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/mycss/footer.css\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- head 안닫음 -->");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
 String chk=(String)request.getAttribute("chk"); 
System.out.println("chk>>"+chk);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-md navbar-dark bg-dark\"\r\n");
      out.write("\taria-label=\"Fourth navbar example\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"home\">OBook</a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-bs-target=\"#navbarsExample04\" aria-controls=\"navbarsExample04\"\r\n");
      out.write("\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" data-interval=\"false\"\r\n");
      out.write("\t\t\tid=\"navbarsExample04\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav me-auto mb-2 mb-md-0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
if(chk.equals("goHome")||chk.equals("goJoin")){
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("\t\t\t\t\taria-current=\"page\" href=\"login\">로그인</a></li>\r\n");
      out.write("\t\t\t\t");
}else if(chk.equals("goLogin")){ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link disabled\" href=\"login\"\r\n");
      out.write("\t\t\t\t\ttabindex=\"-1\" aria-disabled=\"true\">로그인</a></li>\r\n");
      out.write("\t\t\t\t");
}  
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
if(chk.equals("goHome")||chk.equals("goLogin")){
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("\t\t\t\t\taria-current=\"page\" href=\"join\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t");
}else if(chk.equals("goJoin")){   
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link disabled\" href=\"join\"\r\n");
      out.write("\t\t\t\t\ttabindex=\"-1\" aria-disabled=\"true\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t");

						}
				 
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active obookYoutube\"\r\n");
      out.write("\t\t\t\t\taria-current=\"page\" href=\"#\">Obook Youtube</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--   <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link disabled\" href=\"#\" tabindex=\"-1\" aria-disabled=\"true\">Disabled</a>\r\n");
      out.write("          </li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<div class=\"join-div\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"joinUser\" method=\"post\" id=\"form_id\" class=\"join_form\" onsubmit=\"return chk_result()\"\r\n");
      out.write("\t\t name=\"form_name\"  autocomplete='off'>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"join_form_title\">sign up</div>\r\n");
      out.write("\t\t\t<div class=\"input_frame\">\t\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"NAME\" name=\"input_name\"\r\n");
      out.write("\t\t\t\t\tautocomplete='off' id=\"input_name\" class=\"join_input\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"ID\" name=\"input_id\"\r\n");
      out.write("\t\t\t\t\tid=\"input_id\" autocomplete='off' class=\"join_input join_input_id\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 아이디 중복체크 필요 -->\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"중복확인\" class=\"chk_id\" />\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"password\" placeholder=\"PASSWORD\" name=\"input_pwd\"\r\n");
      out.write("\t\t\t\t\tautocomplete='off' class=\"input_pwd join_input\" id=\"input_pwd\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"password\" placeholder=\"PASSWORD CHECK\" autocomplete='off'\r\n");
      out.write("\t\t\t\t\tclass=\"input_pwd join_input\" id=\"input_pwd_re\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 비밀번호 동일시 여부 체크  -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"EMAIL\" name=\"input_email\"\r\n");
      out.write("\t\t\t\t\tautocomplete='off' id=\"input_email\" class=\"join_input\">\r\n");
      out.write("\t\t\t\t<input type=\"tel\" placeholder=\"PHONE\" name=\"input_phone\"\r\n");
      out.write("\t\t\t\t\tautocomplete='off' id=\"input_phone\" class=\"join_input\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"가입\" class=\"join_submit_btn\"/>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"뒤로가기\" onclick=\"history.back()\" class=\"join_submit_btn\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var chk_id_flag=false;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('.chk_id').on('click', function() {\r\n");
      out.write("\t\r\n");
      out.write("\tconsole.log($('#input_id').val());\r\n");
      out.write("\tif($('#input_id').val()==''){\r\n");
      out.write("\t\talert('아이디를 입력해주세요');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar form = {\r\n");
      out.write("\t\tid : $('#input_id').val()\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"chk_id\",\r\n");
      out.write("\t\ttype : \"POST\",\r\n");
      out.write("\t\tdata : form,\r\n");
      out.write("\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(data=='아이디 중복'){\r\n");
      out.write("\t\t\t\talert('아이디가 중복됩니다.');\r\n");
      out.write("\t\t\t\tchk_id_flag=false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\talert('사용가능한 아이디');\r\n");
      out.write("\t\t\t\tchk_id_flag=true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function() {\r\n");
      out.write("\t\t\talert(\"simpleWithObject err\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function chk_result(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar pw_1=$('#input_pwd').val();\r\n");
      out.write("\tvar pw_2=$('#input_pwd_re').val();\r\n");
      out.write("\t\r\n");
      out.write("\tif(chk_id_flag==false){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert('아이디 중복 체크를 해주세요');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(pw_1==pw_2){\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\talert('비밀번호가 일치하지 않습니다');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"footer-left\">\r\n");
      out.write("\t\t<div>대표자명 : 김영주</div>\r\n");
      out.write("\t\t<div>대표번호 : 02-2635-5125</div>\r\n");
      out.write("\t\t<div>팩스번호 : 0504-386-6896</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"footer-right\">\r\n");
      out.write("\t\t<div>서울특별시 구로구 디지털로 30길 28, 8층 828호</div>\r\n");
      out.write("\t\t<div>전자우편주소 : open-book@naver.com</div>\r\n");
      out.write("\t\t<div>사업자 등록번호 891-27-00515</div>\r\n");
      out.write("\t\t<div>통신판매업 신고번호 제 2020-서울구로-0527호</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
